#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

sudo cpupower frequency-set -g performance

if [ $2 = "xfce" ]; then
    exec xfwm4 & startxfce4
elif [ $2 = "xfrat" ]; then
    feh --bg-scale /home/shadefox/Documents/Devil_Daggers.png
    exec ratpoison & startxfce4
fi
