# Shell variables
# Generated by 'wal'
wallpaper='/home/shadefox/.config/wpg/wallpapers/Devil_Daggers.png'

# Special
background='#000000'
foreground='#ffffff'
cursor='#ffffff'

# Colors
color0='#000000'
color1='#BF5238'
color2='#DB632E'
color3='#333333'
color4='#79838A'
color5='#79838A'
color6='#F59533'
color7='#A84F2E'
color8='#BF5238'
color9='#F0BE5D'
color10='#F59533'
color11='#333333'
color12='#ff9900'
color13='#A84F2E'
color14='#DB632E'
color15='#ffffff'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
